import re
import unicodedata
from collections import namedtuple

GenderResult = namedtuple("GenderResult", ["gender", "confidence", "source"])

COMPOUND_OVERRIDES = {
    "MARIA JOSE": "FEMENINO",
    "MARIA JESUS": "FEMENINO",
    "JOSE MARIA": "MASCULINO",
    "MARIA DEL CARMEN": "FEMENINO",
    "MARIA DE LOS ANGELES": "FEMENINO",
    "MARIA DE LA LUZ": "FEMENINO",
    "MARIA DEL PILAR": "FEMENINO",
    "MARIA FERNANDA": "FEMENINO",
    "MARIA TERESA": "FEMENINO",
    "MARIA CRISTINA": "FEMENINO",
    "MARIA ELENA": "FEMENINO",
    "MARIA ANGELICA": "FEMENINO",
    "MARIA ISABEL": "FEMENINO",
    "MARIA LUISA": "FEMENINO",
    "MARIA SOLEDAD": "FEMENINO",
    "MARIA ANTONIA": "FEMENINO",
    "MARIA EMILIA": "FEMENINO",
    "MARIA ALEJANDRA": "FEMENINO",
    "MARIA GRACIA": "FEMENINO",
    "MARIA BELEN": "FEMENINO",
    "MARIA VICTORIA": "FEMENINO",
    "MARIA PAULA": "FEMENINO",
    "MARIA JOSE DE": "FEMENINO",
    "LUIS MARIA": "MASCULINO",
    "JOSE LUIS": "MASCULINO",
    "JOSE MANUEL": "MASCULINO",
    "JOSE ANTONIO": "MASCULINO",
    "JOSE MIGUEL": "MASCULINO",
    "JOSE IGNACIO": "MASCULINO",
    "JUAN CARLOS": "MASCULINO",
    "JUAN PABLO": "MASCULINO",
    "JUAN MANUEL": "MASCULINO",
    "JUAN DIEGO": "MASCULINO",
    "LUIS FERNANDO": "MASCULINO",
    "LUIS ALBERTO": "MASCULINO",
    "CARLOS ALBERTO": "MASCULINO",
    "CARLOS ANDRES": "MASCULINO",
    "PABLO ANDRES": "MASCULINO",
    "FELIPE IGNACIO": "MASCULINO",
    "FELIPE ANDRES": "MASCULINO",
    "FRANCISCO JAVIER": "MASCULINO",
    "MIGUEL ANGEL": "MASCULINO",
    "VICTOR MANUEL": "MASCULINO",
    "RAUL ALBERTO": "MASCULINO",
    "EDUARDO ANTONIO": "MASCULINO",
    "ALEXIS ANDRES": "MASCULINO",
    "CLAUDIO ANDRES": "MASCULINO",
    "CRISTIAN ANDRES": "MASCULINO",
    "MAURICIO ANDRES": "MASCULINO",
    "RODRIGO ANDRES": "MASCULINO",
    "HECTOR MANUEL": "MASCULINO",
    "SEBASTIAN IGNACIO": "MASCULINO",
    "ENRIQUE ALBERTO": "MASCULINO",
    "PEDRO ANTONIO": "MASCULINO",
    "MARCO ANTONIO": "MASCULINO",
}

GENDER_MAP = {
    "JUAN": "MASCULINO",
    "JOSE": "MASCULINO",
    "LUIS": "MASCULINO",
    "CARLOS": "MASCULINO",
    "JORGE": "MASCULINO",
    "PEDRO": "MASCULINO",
    "PABLO": "MASCULINO",
    "DIEGO": "MASCULINO",
    "ANDRES": "MASCULINO",
    "JAVIER": "MASCULINO",
    "FRANCISCO": "MASCULINO",
    "MANUEL": "MASCULINO",
    "RAFAEL": "MASCULINO",
    "MIGUEL": "MASCULINO",
    "ANGEL": "MASCULINO",
    "GABRIEL": "MASCULINO",
    "ALEJANDRO": "MASCULINO",
    "RODRIGO": "MASCULINO",
    "RICARDO": "MASCULINO",
    "PATRICIO": "MASCULINO",
    "CLAUDIO": "MASCULINO",
    "CRISTIAN": "MASCULINO",
    "MAURICIO": "MASCULINO",
    "EDUARDO": "MASCULINO",
    "FERNANDO": "MASCULINO",
    "SERGIO": "MASCULINO",
    "OSCAR": "MASCULINO",
    "HUGO": "MASCULINO",
    "RAUL": "MASCULINO",
    "MARIO": "MASCULINO",
    "JULIO": "MASCULINO",
    "CESAR": "MASCULINO",
    "MARCO": "MASCULINO",
    "ANTONIO": "MASCULINO",
    "DAVID": "MASCULINO",
    "DANIEL": "MASCULINO",
    "FELIPE": "MASCULINO",
    "IGNACIO": "MASCULINO",
    "VICENTE": "MASCULINO",
    "JOAQUIN": "MASCULINO",
    "SEBASTIAN": "MASCULINO",
    "BENJAMIN": "MASCULINO",
    "MATIAS": "MASCULINO",
    "TOMAS": "MASCULINO",
    "MARTIN": "MASCULINO",
    "NICOLAS": "MASCULINO",
    "CRISTOBAL": "MASCULINO",
    "ALVARO": "MASCULINO",
    "ALEXIS": "MASCULINO",
    "FABIAN": "MASCULINO",
    "HECTOR": "MASCULINO",
    "IVAN": "MASCULINO",
    "JAIME": "MASCULINO",
    "RENE": "MASCULINO",
    "VICTOR": "MASCULINO",
    "ALBERTO": "MASCULINO",
    "ALFREDO": "MASCULINO",
    "ARTURO": "MASCULINO",
    "CAMILO": "MASCULINO",
    "DARIO": "MASCULINO",
    "ELIAS": "MASCULINO",
    "EMILIO": "MASCULINO",
    "ENRIQUE": "MASCULINO",
    "ESTEBAN": "MASCULINO",
    "FEDERICO": "MASCULINO",
    "GONZALO": "MASCULINO",
    "GUSTAVO": "MASCULINO",
    "HERNAN": "MASCULINO",
    "JOEL": "MASCULINO",
    "JONATHAN": "MASCULINO",
    "KEVIN": "MASCULINO",
    "LEONARDO": "MASCULINO",
    "LORENZO": "MASCULINO",
    "LUCAS": "MASCULINO",
    "LUCIANO": "MASCULINO",
    "MARCELO": "MASCULINO",
    "MARCOS": "MASCULINO",
    "MAXIMILIANO": "MASCULINO",
    "NELSON": "MASCULINO",
    "NESTOR": "MASCULINO",
    "OMAR": "MASCULINO",
    "ORLANDO": "MASCULINO",
    "REINALDO": "MASCULINO",
    "RENATO": "MASCULINO",
    "ROBERTO": "MASCULINO",
    "ROLANDO": "MASCULINO",
    "RUBEN": "MASCULINO",
    "SALOMON": "MASCULINO",
    "SAMUEL": "MASCULINO",
    "SIMON": "MASCULINO",
    "VLADIMIR": "MASCULINO",
    "WILSON": "MASCULINO",
    "YERKO": "MASCULINO",
    "MARIA": "FEMENINO",
    "ANDREA": "FEMENINO",
    "CARMEN": "FEMENINO",
    "PATRICIA": "FEMENINO",
    "CLAUDIA": "FEMENINO",
    "CAROLINA": "FEMENINO",
    "DANIELA": "FEMENINO",
    "FRANCISCA": "FEMENINO",
    "GABRIELA": "FEMENINO",
    "ISABEL": "FEMENINO",
    "JAVIERA": "FEMENINO",
    "KATHERINE": "FEMENINO",
    "LAURA": "FEMENINO",
    "MARGARITA": "FEMENINO",
    "NATALIA": "FEMENINO",
    "PAMELA": "FEMENINO",
    "SANDRA": "FEMENINO",
    "TERESA": "FEMENINO",
    "VERONICA": "FEMENINO",
    "ALEJANDRA": "FEMENINO",
    "ANA": "FEMENINO",
    "BARBARA": "FEMENINO",
    "BEATRIZ": "FEMENINO",
    "CAMILA": "FEMENINO",
    "CARLA": "FEMENINO",
    "CATALINA": "FEMENINO",
    "CRISTINA": "FEMENINO",
    "ELENA": "FEMENINO",
    "ELIZABETH": "FEMENINO",
    "EMMA": "FEMENINO",
    "ESTER": "FEMENINO",
    "EVELYN": "FEMENINO",
    "FERNANDA": "FEMENINO",
    "GLORIA": "FEMENINO",
    "GRACIELA": "FEMENINO",
    "INGRID": "FEMENINO",
    "JACQUELINE": "FEMENINO",
    "JESSICA": "FEMENINO",
    "JUANA": "FEMENINO",
    "KAREN": "FEMENINO",
    "LARISSA": "FEMENINO",
    "LEONOR": "FEMENINO",
    "LORENA": "FEMENINO",
    "LUISA": "FEMENINO",
    "MACARENA": "FEMENINO",
    "MAGDALENA": "FEMENINO",
    "MARCELA": "FEMENINO",
    "MONICA": "FEMENINO",
    "NICOLE": "FEMENINO",
    "OLGA": "FEMENINO",
    "PAOLA": "FEMENINO",
    "PAULINA": "FEMENINO",
    "PAULA": "FEMENINO",
    "RAQUEL": "FEMENINO",
    "ROSA": "FEMENINO",
    "RUTH": "FEMENINO",
    "SARA": "FEMENINO",
    "SILVIA": "FEMENINO",
    "SOFIA": "FEMENINO",
    "SUSANA": "FEMENINO",
    "VALERIA": "FEMENINO",
    "VICTORIA": "FEMENINO",
    "VIVIANA": "FEMENINO",
    "YOLANDA": "FEMENINO",
    "AMALIA": "FEMENINO",
    "AMELIA": "FEMENINO",
    "ANGELICA": "FEMENINO",
    "ANTONIETA": "FEMENINO",
    "BELEN": "FEMENINO",
    "BERNARDITA": "FEMENINO",
    "BETSABE": "FEMENINO",
    "CONSTANZA": "FEMENINO",
    "DENISSE": "FEMENINO",
    "DIAMELA": "FEMENINO",
    "DIANA": "FEMENINO",
    "DOMINGA": "FEMENINO",
    "ELIANA": "FEMENINO",
    "ELISA": "FEMENINO",
    "EMILIA": "FEMENINO",
    "ESPERANZA": "FEMENINO",
    "ESTRELLA": "FEMENINO",
    "EUGENIA": "FEMENINO",
    "EULALIA": "FEMENINO",
    "FABIOLA": "FEMENINO",
    "FLORENCIA": "FEMENINO",
    "GENOVEVA": "FEMENINO",
    "GISELA": "FEMENINO",
    "HELENA": "FEMENINO",
    "HORTENSIA": "FEMENINO",
    "IRENE": "FEMENINO",
    "JENNY": "FEMENINO",
    "JOHANNA": "FEMENINO",
    "JUDITH": "FEMENINO",
    "JULIA": "FEMENINO",
    "JULIETA": "FEMENINO",
    "LETICIA": "FEMENINO",
    "LIDIA": "FEMENINO",
    "LILIANA": "FEMENINO",
    "LINDA": "FEMENINO",
    "LUCIA": "FEMENINO",
    "LUZ": "FEMENINO",
    "MANUELA": "FEMENINO",
    "MARIANA": "FEMENINO",
    "MARISOL": "FEMENINO",
    "MARTA": "FEMENINO",
    "MELISA": "FEMENINO",
    "MERCEDES": "FEMENINO",
    "MYRIAM": "FEMENINO",
    "NANCY": "FEMENINO",
    "NOELIA": "FEMENINO",
    "NOEMI": "FEMENINO",
    "NORMA": "FEMENINO",
    "ORIANA": "FEMENINO",
    "REMEDIOS": "FEMENINO",
    "REBECA": "FEMENINO",
    "ROCIO": "FEMENINO",
    "ROMINA": "FEMENINO",
    "ROSARIO": "FEMENINO",
    "SABRINA": "FEMENINO",
    "SCARLET": "FEMENINO",
    "SOLEDAD": "FEMENINO",
    "TAMARA": "FEMENINO",
    "URSULA": "FEMENINO",
    "VALENTINA": "FEMENINO",
    "YANET": "FEMENINO",
    "YESSENIA": "FEMENINO",
    "YOCELYN": "FEMENINO",
    "YOHANA": "FEMENINO",
    "ZULEMA": "FEMENINO",
}


def _normalize(name: str) -> str:
    return unicodedata.normalize("NFKD", name.upper()).encode("ascii", "ignore").decode()


def infer_gender(nombres: str | None) -> str:
    result = infer_gender_scored(nombres)
    return result.gender


def infer_gender_scored(nombres: str | None) -> GenderResult:
    if not nombres:
        return GenderResult(gender="NO ENCONTRADO", confidence=0.0, source="none")
    parts = nombres.strip().split()
    full_clean = _normalize(" ".join(parts))
    # Check full name first (any word count), then 3-word, then 2-word
    for n_words in (len(parts), 3, 2):
        key = " ".join(full_clean.split()[:n_words])
        if key in COMPOUND_OVERRIDES:
            return GenderResult(gender=COMPOUND_OVERRIDES[key], confidence=1.0, source="compound")

    first_name_clean = _normalize(parts[0])
    if first_name_clean in GENDER_MAP:
        return GenderResult(gender=GENDER_MAP[first_name_clean], confidence=1.0, source="name_map")

    return GenderResult(gender="NO ENCONTRADO", confidence=0.0, source="none")


def infer_gender_from_text(text: str) -> str:
    result = infer_gender_from_text_scored(text)
    return result.gender


def infer_gender_from_text_scored(text: str) -> GenderResult:
    text_lower = text.lower()
    if re.search(r'\bsexo\s*:?\s*(masculino|m|varon|hombre)\b', text_lower):
        return GenderResult(gender="MASCULINO", confidence=0.7, source="text_sexo")
    if re.search(r'\bsexo\s*:?\s*(femenino|f|mujer)\b', text_lower):
        return GenderResult(gender="FEMENINO", confidence=0.7, source="text_sexo")
    if re.search(r'\b(sr\.?|don|señor)\s', text_lower):
        return GenderResult(gender="MASCULINO", confidence=0.6, source="text_honorific")
    if re.search(r'\b(sra\.?|srita\.?|doña|señora)\s', text_lower):
        return GenderResult(gender="FEMENINO", confidence=0.6, source="text_honorific")
    return GenderResult(gender="NO ENCONTRADO", confidence=0.0, source="none")
